version: "3"

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - mongo-data:/data/db
      - "$PWD/scripts/docker/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"

volumes:
  mongo-data:
